-- helps determine is a blood pact can magic burst or not

return {
  [513] = { id = 513, en = "Poison Nails", damage = "physical" },
  [516] = { id = 516, en = "Meteorite", damage = "magic" },
  [518] = { id = 518, en = "Searing Light", damage = "physical" },
  [519] = { id = 519, en = "Holy Mist", damage = "magic" },
  [521] = { id = 521, en = "Regal Scratch", damage = "physical" },
  [524] = { id = 524, en = "Level ? Holy", damage = "magic" },
  [528] = { id = 528, en = "Moonlit Charge", damage = "physical" },
  [529] = { id = 529, en = "Crescent Fang", damage = "physical" },
  [534] = { id = 534, en = "Eclipse Bite", damage = "physical" },
  [536] = { id = 536, en = "Howling Moon", damage = "physical" },
  [537] = { id = 537, en = "Lunar Bay", damage = "magic" },
  [539] = { id = 539, en = "Impact", damage = "magic" },
  [544] = { id = 544, en = "Punch", damage = "physical" },
  [545] = { id = 545, en = "Fire II", damage = "magic" },
  [546] = { id = 546, en = "Burning Strike", damage = "physical" },
  [547] = { id = 547, en = "Double Punch", damage = "physical" },
  [549] = { id = 549, en = "Fire IV", damage = "magic" },
  [550] = { id = 550, en = "Flaming Crush", damage = "physical" },
  [551] = { id = 551, en = "Meteor Strike", damage = "magic" },
  [552] = { id = 552, en = "Inferno", damage = "physical" },
  [554] = { id = 554, en = "Conflag Strike", damage = "magic" },
  [560] = { id = 560, en = "Rock Throw", damage = "physical" },
  [561] = { id = 561, en = "Stone II", damage = "magic" },
  [562] = { id = 562, en = "Rock Buster", damage = "physical" },
  [563] = { id = 563, en = "Megalith Throw", damage = "physical" },
  [565] = { id = 565, en = "Stone IV", damage = "magic" },
  [566] = { id = 566, en = "Mountain Buster", damage = "physical" },
  [567] = { id = 567, en = "Geocrush", damage = "magic" },
  [568] = { id = 568, en = "Earthen Fury", damage = "physical" },
  [570] = { id = 570, en = "Crag Throw", damage = "physical" },
  [576] = { id = 576, en = "Barracuda Dive", damage = "physical" },
  [577] = { id = 577, en = "Water II", damage = "magic" },
  [578] = { id = 578, en = "Tail Whip", damage = "physical" },
  [581] = { id = 581, en = "Water IV", damage = "magic" },
  [582] = { id = 582, en = "Spinning Dive", damage = "physical" },
  [583] = { id = 583, en = "Grand Fall", damage = "magic" },
  [584] = { id = 584, en = "Tidal Wave", damage = "physical" },
  [592] = { id = 592, en = "Claw", damage = "physical" },
  [593] = { id = 593, en = "Aero II", damage = "magic" },
  [597] = { id = 597, en = "Aero IV", damage = "magic" },
  [598] = { id = 598, en = "Predator Claws", damage = "physical" },
  [599] = { id = 599, en = "Wind Blade", damage = "magic" },
  [600] = { id = 600, en = "Aerial Blast", damage = "physical" },
  [608] = { id = 608, en = "Axe Kick", damage = "physical" },
  [609] = { id = 609, en = "Blizzard II", damage = "magic" },
  [612] = { id = 612, en = "Double Slap", damage = "physical" },
  [613] = { id = 613, en = "Blizzard IV", damage = "magic" },
  [614] = { id = 614, en = "Rush", damage = "physical" },
  [615] = { id = 615, en = "Heavenly Strike", damage = "magic" },
  [616] = { id = 616, en = "Diamond Dust", damage = "physical" },
  [624] = { id = 624, en = "Shock Strike", damage = "physical" },
  [625] = { id = 625, en = "Thunder II", damage = "magic" },
  [627] = { id = 627, en = "Thunderspark", damage = "magic" },
  [629] = { id = 629, en = "Thunder IV", damage = "magic" },
  [630] = { id = 630, en = "Chaotic Strike", damage = "physical" },
  [631] = { id = 631, en = "Thunderstorm", damage = "magic" },
  [632] = { id = 632, en = "Judgment Bolt", damage = "physical" },
  [634] = { id = 634, en = "Volt Strike", damage = "physical" },
  [656] = { id = 656, en = "Camisado", damage = "physical" },
  [662] = { id = 662, en = "Nether Blast", damage = "magic" },
  [663] = { id = 663, en = "Cacodemonia", damage = "physical" },
  [664] = { id = 664, en = "Ruinous Omen", damage = "physical" },
  [665] = { id = 665, en = "Night Terror", damage = "magic" },
  [667] = { id = 667, en = "Blindside", damage = "physical" },
  [668] = { id = 668, en = "Deconstruction", damage = "physical" },
  [669] = { id = 669, en = "Chronoshift", damage = "physical" },
  [670] = { id = 670, en = "Zantetsuken", damage = "magic" },
  [671] = { id = 671, en = "Perfect Defense", damage = "physical" },
  [780] = { id = 780, en = "Regal Gash", damage = "physical" },
  [960] = { id = 960, en = "Clarsach Call", damage = "physical" },
  [961] = { id = 961, en = "Welt", damage = "physical" },
  [964] = { id = 964, en = "Roundhouse", damage = "physical" },
  [967] = { id = 967, en = "Sonic Buffet", damage = "magic" },
  [968] = { id = 968, en = "Tornado II", damage = "magic" },
  [970] = { id = 970, en = "Hysteric Assault", damage = "physical" },
}
