return {
  [577] = { id = 577, en = "Foot Kick", skillchain_a = "Detonation", skillchain_b = "", skillchain_c = "" },
  [597] = { id = 597, en = "Sprout Smack", skillchain_a = "Reverberation", skillchain_b = "", skillchain_c = "" },
  [603] = { id = 603, en = "Wild Oats", skillchain_a = "Transfixion", skillchain_b = "", skillchain_c = "" },
  [551] = { id = 551, en = "Power Attack", skillchain_a = "Reverberation", skillchain_b = "", skillchain_c = "" },
  [599] = { id = 599, en = "Queasyshroom", skillchain_a = "Compression", skillchain_b = "", skillchain_c = "" },
  [620] = { id = 620, en = "Battle Dance", skillchain_a = "Impaction", skillchain_b = "", skillchain_c = "" },
  [638] = { id = 638, en = "Feather Storm", skillchain_a = "Transfixion", skillchain_b = "", skillchain_c = "" },
  [623] = { id = 623, en = "Head Butt", skillchain_a = "Impaction", skillchain_b = "", skillchain_c = "" },
  [567] = { id = 567, en = "Helldive", skillchain_a = "Transfixion", skillchain_b = "", skillchain_c = "" },
  [529] = { id = 529, en = "Bludgeon", skillchain_a = "Liquefaction", skillchain_b = "", skillchain_c = "" },
  [587] = { id = 587, en = "Claw Cyclone", skillchain_a = "Scission", skillchain_b = "", skillchain_c = "" },
  [519] = { id = 519, en = "Screwdriver", skillchain_a = "Transfixion", skillchain_b = "Scission", skillchain_c = "" },
  [622] = { id = 622, en = "Grand Slam", skillchain_a = "Induration", skillchain_b = "", skillchain_c = "" },
  [527] = { id = 527, en = "Smite of Rage", skillchain_a = "Detonation", skillchain_b = "", skillchain_c = "" },
  [596] = { id = 596, en = "Pinecone Bomb", skillchain_a = "Liquefaction", skillchain_b = "", skillchain_c = "" },
  [569] = { id = 569, en = "Jet Stream", skillchain_a = "Impaction", skillchain_b = "", skillchain_c = "" },
  [594] = { id = 594, en = "Uppercut", skillchain_a = "Liquefaction", skillchain_b = "Impaction", skillchain_c = "" },
  [539] = { id = 539, en = "Terror Touch", skillchain_a = "Compression", skillchain_b = "Reverberation", skillchain_c = "" },
  [543] = { id = 543, en = "Mandibular Bite", skillchain_a = "Induration", skillchain_b = "", skillchain_c = "" },
  [545] = { id = 545, en = "Sickle Slash", skillchain_a = "Compression", skillchain_b = "", skillchain_c = "" },
  [589] = { id = 589, en = "Dimensional Death", skillchain_a = "Impaction", skillchain_b = "", skillchain_c = "" },
  [652] = { id = 652, en = "Spiral Spin", skillchain_a = "Transfixion", skillchain_b = "", skillchain_c = "" },
  [554] = { id = 554, en = "Death Scissors", skillchain_a = "Compression", skillchain_b = "Reverberation", skillchain_c = "" },
  [650] = { id = 650, en = "Seedspray", skillchain_a = "Induration", skillchain_b = "Detonation", skillchain_c = "" },
  [564] = { id = 564, en = "Body Slam", skillchain_a = "Impaction", skillchain_b = "", skillchain_c = "" },
  [631] = { id = 631, en = "Hydro Shot", skillchain_a = "Reverberation", skillchain_b = "", skillchain_c = "" },
  [628] = { id = 628, en = "Frypan", skillchain_a = "Impaction", skillchain_b = "", skillchain_c = "" },
  [560] = { id = 560, en = "Frenetic Rip", skillchain_a = "Induration", skillchain_b = "", skillchain_c = "" },
  [540] = { id = 540, en = "Spinal Cleave", skillchain_a = "Scission", skillchain_b = "Detonation", skillchain_c = "" },
  [640] = { id = 640, en = "Tail Slap", skillchain_a = "Reverberation", skillchain_b = "", skillchain_c = "" },
  [641] = { id = 641, en = "Hysteric Barrage", skillchain_a = "Detonation", skillchain_b = "", skillchain_c = "" },
  [653] = { id = 653, en = "Asuran Claws", skillchain_a = "Liquefaction", skillchain_b = "Impaction", skillchain_c = "" },
  [643] = { id = 643, en = "Cannonball", skillchain_a = "Fusion", skillchain_b = "", skillchain_c = "" },
  [611] = { id = 611, en = "Disseverment", skillchain_a = "Distortion", skillchain_b = "", skillchain_c = "" },
  [654] = { id = 654, en = "Sub-zero Smash", skillchain_a = "Fragmentation", skillchain_b = "", skillchain_c = "" },
  [585] = { id = 585, en = "Ram Charge", skillchain_a = "Fragmentation", skillchain_b = "", skillchain_c = "" },
  [617] = { id = 617, en = "Vertical Cleave", skillchain_a = "Gravitation", skillchain_b = "", skillchain_c = "" },
  [665] = { id = 665, en = "Final Sting", skillchain_a = "Fusion", skillchain_b = "", skillchain_c = "" },
  [666] = { id = 666, en = "Goblin Rush", skillchain_a = "Fusion", skillchain_b = "Impaction", skillchain_c = "" },
  [667] = { id = 667, en = "Vanity Dive", skillchain_a = "Scission", skillchain_b = "", skillchain_c = "" },
  [669] = { id = 669, en = "Whirl of Rage", skillchain_a = "Scission", skillchain_b = "Detonation", skillchain_c = "" },
  [670] = { id = 670, en = "Benthic Typhoon", skillchain_a = "Gravitation", skillchain_b = "Transfixion", skillchain_c = "" },
  [673] = { id = 673, en = "Quad. Continuum", skillchain_a = "Distortion", skillchain_b = "Scission", skillchain_c = "" },
  [677] = { id = 677, en = "Empty Thrash", skillchain_a = "Compression", skillchain_b = "Scission", skillchain_c = "" },
  [682] = { id = 682, en = "Delta Thrust", skillchain_a = "Liquefaction", skillchain_b = "Detonation", skillchain_c = "" },
  [688] = { id = 688, en = "Heavy Strike", skillchain_a = "Fragmentation", skillchain_b = "Transfixion", skillchain_c = "" },
  [692] = { id = 692, en = "Sudden Lunge", skillchain_a = "Detonation", skillchain_b = "", skillchain_c = "" },
  [693] = { id = 693, en = "Quadrastrike", skillchain_a = "Liquefaction", skillchain_b = "Scission", skillchain_c = "" },
  [740] = { id = 740, en = "Tourbillion", skillchain_a = "Light", skillchain_b = "Fragmentation", skillchain_c = "" },
  [697] = { id = 697, en = "Amorphic Spikes", skillchain_a = "Gravitation", skillchain_b = "Transfixion", skillchain_c = "" },
  [699] = { id = 699, en = "Barbed Crescent", skillchain_a = "Distortion", skillchain_b = "Liquefaction", skillchain_c = "" },
  [742] = { id = 742, en = "Bilgestorm", skillchain_a = "Gravitation", skillchain_b = "", skillchain_c = "" },
  [743] = { id = 743, en = "Bloodrake", skillchain_a = "Darkness", skillchain_b = "Distortion", skillchain_c = "" },
  [706] = { id = 706, en = "Glutinous Dart", skillchain_a = "Fragmentation", skillchain_b = "", skillchain_c = "" },
  [704] = { id = 704, en = "Paralyzing Triad", skillchain_a = "Gravitation", skillchain_b = "", skillchain_c = "" },
  [709] = { id = 709, en = "Thrashing Assault", skillchain_a = "Fusion", skillchain_b = "Impaction", skillchain_c = "" },
  [714] = { id = 714, en = "Sinker Drill", skillchain_a = "Gravitation", skillchain_b = "Reverberation", skillchain_c = "" },
  [723] = { id = 723, en = "Saurian Slide", skillchain_a = "Fragmentation", skillchain_b = "Distortion", skillchain_c = "" },
}
