-- DEFAULT BINDINGS
-- SEE: https://docs.windower.net/commands/keymapping/
---------------------------------------------------------
-- 'EQ' is a special binding for '=' since its not valid XML
-- '#' is a special binding for pure numbers, so it parses correctly
---------------------------------------------------------
-- DO NOT EDIT THIS FILE, CHANGE IN SETTINGS.XML INSTEAD
-- DO NOT EDIT THIS FILE, CHANGE IN SETTINGS.XML INSTEAD
-- DO NOT EDIT THIS FILE, CHANGE IN SETTINGS.XML INSTEAD
---------------------------------------------------------

keybinds = {}
keybinds.R1 = {}
keybinds.R1.C01 = '#1'         -- Hotbar Row #1 Col #1
keybinds.R1.C02 = '#2'         -- Hotbar Row #1 Col #2
keybinds.R1.C03 = '#3'         -- Hotbar Row #1 Col #3
keybinds.R1.C04 = '#4'         -- Hotbar Row #1 Col #4
keybinds.R1.C05 = '#5'         -- Hotbar Row #1 Col #5
keybinds.R1.C06 = '#6'         -- Hotbar Row #1 Col #6
keybinds.R1.C07 = '#7'         -- Hotbar Row #1 Col #7
keybinds.R1.C08 = '#8'         -- Hotbar Row #1 Col #8
keybinds.R1.C09 = '#9'         -- Hotbar Row #1 Col #9
keybinds.R1.C10 = '#0'         -- Hotbar Row #1 Col #10
keybinds.R1.C11 = '`'          -- Hotbar Row #1 Col #11
keybinds.R1.C12 = 'EQ'         -- Hotbar Row #1 Col #12
keybinds.R2 = {}
keybinds.R2.C01 = 'ALT + 1'    -- Hotbar Row #2 Col #1
keybinds.R2.C02 = 'ALT + 2'    -- Hotbar Row #2 Col #2
keybinds.R2.C03 = 'ALT + 3'    -- Hotbar Row #2 Col #3
keybinds.R2.C04 = 'ALT + 4'    -- Hotbar Row #2 Col #4
keybinds.R2.C05 = 'ALT + 5'    -- Hotbar Row #2 Col #5
keybinds.R2.C06 = 'ALT + 6'    -- Hotbar Row #2 Col #6
keybinds.R2.C07 = 'ALT + 7'    -- Hotbar Row #2 Col #7
keybinds.R2.C08 = 'ALT + 8'    -- Hotbar Row #2 Col #8
keybinds.R2.C09 = 'ALT + 9'    -- Hotbar Row #2 Col #9
keybinds.R2.C10 = 'ALT + 0'    -- Hotbar Row #2 Col #10
keybinds.R2.C11 = 'ALT + -'    -- Hotbar Row #2 Col #11
keybinds.R2.C12 = 'ALT + EQ'   -- Hotbar Row #2 Col #12
keybinds.R3 = {}
keybinds.R3.C01 = 'CTRL + 1'   -- Hotbar Row #3 Col #1
keybinds.R3.C02 = 'CTRL + 2'   -- Hotbar Row #3 Col #2
keybinds.R3.C03 = 'CTRL + 3'   -- Hotbar Row #3 Col #3
keybinds.R3.C04 = 'CTRL + 4'   -- Hotbar Row #3 Col #4
keybinds.R3.C05 = 'CTRL + 5'   -- Hotbar Row #3 Col #5
keybinds.R3.C06 = 'CTRL + 6'   -- Hotbar Row #3 Col #6
keybinds.R3.C07 = 'CTRL + 7'   -- Hotbar Row #3 Col #7
keybinds.R3.C08 = 'CTRL + 8'   -- Hotbar Row #3 Col #8
keybinds.R3.C09 = 'CTRL + 9'   -- Hotbar Row #3 Col #9
keybinds.R3.C10 = 'CTRL + 0'   -- Hotbar Row #3 Col #10
keybinds.R3.C11 = 'CTRL + -'   -- Hotbar Row #3 Col #11
keybinds.R3.C12 = 'CTRL + EQ'  -- Hotbar Row #3 Col #12
keybinds.R4 = {}
keybinds.R4.C01 = 'Shift + 1'  -- Hotbar Row #4 Col #1
keybinds.R4.C02 = 'Shift + 2'  -- Hotbar Row #4 Col #2
keybinds.R4.C03 = 'Shift + 3'  -- Hotbar Row #4 Col #3
keybinds.R4.C04 = 'Shift + 4'  -- Hotbar Row #4 Col #4
keybinds.R4.C05 = 'Shift + 5'  -- Hotbar Row #4 Col #5
keybinds.R4.C06 = 'Shift + 6'  -- Hotbar Row #4 Col #6
keybinds.R4.C07 = 'Shift + 7'  -- Hotbar Row #4 Col #7
keybinds.R4.C08 = 'Shift + 8'  -- Hotbar Row #4 Col #8
keybinds.R4.C09 = 'Shift + 9'  -- Hotbar Row #4 Col #9
keybinds.R4.C10 = 'Shift + 0'  -- Hotbar Row #4 Col #10
keybinds.R4.C11 = 'Shift + -'  -- Hotbar Row #4 Col #11
keybinds.R4.C12 = 'Shift + EQ' -- Hotbar Row #4 Col #12
keybinds.R5 = {}
keybinds.R5.C01 = 'Shift + q'  -- Hotbar Row #5 Col #1
keybinds.R5.C02 = 'Shift + w'  -- Hotbar Row #5 Col #2
keybinds.R5.C03 = 'Shift + e'  -- Hotbar Row #5 Col #3
keybinds.R5.C04 = 'Shift + r'  -- Hotbar Row #5 Col #4
keybinds.R5.C05 = 'Shift + t'  -- Hotbar Row #5 Col #5
keybinds.R5.C06 = 'Shift + y'  -- Hotbar Row #5 Col #6
keybinds.R5.C07 = 'Shift + u'  -- Hotbar Row #5 Col #7
keybinds.R5.C08 = 'Shift + i'  -- Hotbar Row #5 Col #8
keybinds.R5.C09 = 'Shift + o'  -- Hotbar Row #5 Col #9
keybinds.R5.C10 = 'Shift + p'  -- Hotbar Row #5 Col #10
keybinds.R5.C11 = 'Shift + ['  -- Hotbar Row #5 Col #11
keybinds.R5.C12 = 'Shift + ]'  -- Hotbar Row #5 Col #12
keybinds.R6 = {}
keybinds.R6.C01 = 'Alt + q'    -- Hotbar Row #6 Col #1
keybinds.R6.C02 = 'Alt + w'    -- Hotbar Row #6 Col #2
keybinds.R6.C03 = 'Alt + e'    -- Hotbar Row #6 Col #3
keybinds.R6.C04 = 'Alt + r'    -- Hotbar Row #6 Col #4
keybinds.R6.C05 = 'Alt + t'    -- Hotbar Row #6 Col #5
keybinds.R6.C06 = 'Alt + y'    -- Hotbar Row #6 Col #6
keybinds.R6.C07 = 'Alt + u'    -- Hotbar Row #6 Col #7
keybinds.R6.C08 = 'Alt + i'    -- Hotbar Row #6 Col #8
keybinds.R6.C09 = 'Alt + o'    -- Hotbar Row #6 Col #9
keybinds.R6.C10 = 'Alt + p'    -- Hotbar Row #6 Col #10
keybinds.R6.C11 = 'Alt + ['    -- Hotbar Row #6 Col #11
keybinds.R6.C12 = 'Alt + ]'    -- Hotbar Row #6 Col #12


return keybinds
